import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#767775",
        "outline-variant": "#adadab",
        "surface-container-low": "#f1f1ee",
        "error-container": "#f95630",
        "error": "#b02500",
        "on-background": "#2e2f2d",
        "primary-fixed": "#fd9000",
        "surface-bright": "#f7f6f3",
        "on-error-container": "#520c00",
        "secondary-fixed": "#8df5e4",
        "on-secondary-container": "#005c53",
        "on-primary-fixed-variant": "#532b00",
        "secondary-fixed-dim": "#7fe6d5",
        "tertiary-dim": "#5f4e00",
        "tertiary": "#6d5a00",
        "surface-container-lowest": "#ffffff",
        "secondary": "#00675c",
        "on-tertiary-fixed-variant": "#675500",
        "tertiary-fixed": "#fdd73e",
        "primary-dim": "#794200",
        "inverse-primary": "#fd9000",
        "inverse-surface": "#0d0f0d",
        "primary": "#8a4c00",
        "primary-container": "#fd9000",
        "on-tertiary-container": "#5c4b00",
        "surface-container": "#e8e8e5",
        "on-primary-container": "#462400",
        "surface-tint": "#8a4c00",
        "secondary-dim": "#005a50",
        "on-primary-fixed": "#1e0c00",
        "on-secondary-fixed-variant": "#00675c",
        "error-dim": "#b92902",
        "secondary-container": "#8df5e4",
        "on-tertiary": "#fff2cf",
        "surface-dim": "#d4d5d1",
        "tertiary-fixed-dim": "#eec930",
        "on-surface": "#2e2f2d",
        "on-secondary-fixed": "#004840",
        "primary-fixed-dim": "#ea8400",
        "on-primary": "#fff0e6",
        "surface": "#f7f6f3",
        "background": "#f7f6f3",
        "on-surface-variant": "#5b5c5a",
        "tertiary-container": "#fdd73e",
        "inverse-on-surface": "#9d9d9b",
        "surface-container-highest": "#ddddda",
        "surface-variant": "#ddddda",
        "surface-container-high": "#e2e3df",
        "on-error": "#ffefec",
        "on-tertiary-fixed": "#463900",
        "on-secondary": "#c0fff3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
} satisfies Config;
